services:
  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: wordle
      POSTGRES_PASSWORD: wordle
      POSTGRES_DB: wordle
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
